BugFix: fastmath warning breaks w AttrErr
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

Bug and fix described at"

http://stackoverflow.com/questions/20881768/fastmath-error-in-python-have-decl-mpz-powm-sec